name: Build and Deploy Function App to Azure

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
          cd Day3/function-app-code
          npm install

      - name: Build Function App
        run: |
          cd Day3/function-app-code
          npm run build --if-present

      - name: Upload Function Artifact
        uses: actions/upload-artifact@v4
        with:
          name: functionapp-build
          path: Day3/function-app-code


  deploy:
    runs-on: ubuntu-latest

    needs: build

    permissions:
      id-token: write
      contents: read

    steps:

      - name: Download Function Artifact
        uses: actions/download-artifact@v4
        with:
          name: functionapp-build

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: 'function-app-001'
          package: .
